apiVersion: v1
kind: ReplicationController
metadata:
  name: run-melody
spec:
  replicas: 10
  selector:
    name: run-melody
  template:
    metadata:
      labels:
        name: run-melody
    spec:
      containers:
      - image: gcr.io/run-melody/run-melody:latest
        name: run-melody
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: run-melody
